name: stream of thoughts
favicon: null
layout_spectrum: 0.19945940584875643
typography_spectrum: 0.13933
title: stream of thoughts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.14433805155567825
  lightness: 0.37680313386954367
  saturation: 0.7533969499636441
  rhythmicContrast: 0.6794093679636717
purpose: []
